### ISSUE TITLE
[FEATURE]Modify only one position

### ISSUE THREAD

**Issue by nvonwolff** [EPiCs-group/chemspax#10]
**Is your feature request related to a problem? Please describe.**
It seems that currently it is not possible to generate a database of structures, where only one position in the initial skeleton is functionalized with a set of substituents. That would be highly beneficial to study the influence of substituents at specific ligand positions in a complex

**Describe the solution you'd like**
It would be great if only one specific position could be functionalized, with one substituent at a time. E.g. turning a specific C-H bond into a set of C-X groups with different Xs. 

**Additional context**

**Comment by akalikadien** [comment]
Dear Niklas, 

With the new Pythonic version of ChemSpaX this is possible. In this case I'm working on a random location on my pc. The following steps were taken:

1. Follow instructions to create a conda environment and install ChemSpaX
2. Create a file called test_functionalization_same_skeleton.py and paste code from below in it
3. Create skeleton/ folder in same directory where this python file is located
4. Copy RuPNP.xyz and RuPNP.mol from ChemSpaX's skeleton_temp folder to this skeleton/ folder
5. Create folder called functionalized_complexes/ in same directory as this python file and create a folder called done/ within the functionalized_complexes/ folder
6. Run code `python test_functionalization_same_skeleton.py`

This code should take the same skeleton and same functionalization site, but place different groups on those sites such that you can compare the effects across the same skeleton. This code is of course a simple example, but feel free to adapt and improve it!

```python
import os
import glob
from chemspax.main import main
import shutil


def move_functionalized_complexes(path_to_functionalized_complexes, path_to_target, substituent_list):
    functionalized_complexes_xyz = glob.glob(os.path.join(path_to_functionalized_complexes, '*.xyz'))
    functionalized_complexes_mol = glob.glob(os.path.join(path_to_functionalized_complexes, '*.mol'))

    for complex_xyz, substituent in zip(functionalized_complexes_xyz, substituent_list):
        filename = os.path.basename(os.path.normpath(complex_xyz)).split(".")[0]
        shutil.move(complex_xyz, os.path.join(path_to_target, filename + "_" + substituent + ".xyz"))

    for complex_mol, substituent in zip(functionalized_complexes_mol, substituent_list):
        filename = os.path.basename(os.path.normpath(complex_mol)).split(".")[0]
        shutil.move(complex_mol, os.path.join(path_to_target, filename + "_" + substituent + ".mol"))

current_directory = os.getcwd()
chemspax_dir = "/home/akalikadien/chemspax/chemspax"

path_to_substituents = os.path.join(chemspax_dir, "substituents_xyz", "manually_generated/")  # should always point to the chemspax/substituents_xyz/manually_generated folder
path_to_database = os.path.join(path_to_substituents, "central_atom_centroid_database.csv")

substituent_list = ["CH3", "CH3"]
skeleton_list = glob.glob(os.path.join(current_directory, "skeletons", "*.xyz"))
path_to_skeletons = os.path.join(current_directory, "skeletons")
working_directory = current_directory
path_to_output = os.path.join(current_directory, "functionalized_complexes")
main(skeleton_list, substituent_list, path_to_database, path_to_substituents, path_to_skeletons, working_directory, path_to_output)

target_path = os.path.join(path_to_output, "done")
move_functionalized_complexes(path_to_functionalized_complexes=path_to_output, path_to_target=target_path, substituent_list=substituent_list)

substituent_list = ["C6H6", "C6H6"]
main(skeleton_list, substituent_list, path_to_database, path_to_substituents, path_to_skeletons, working_directory, path_to_output)
move_functionalized_complexes(path_to_functionalized_complexes=path_to_output, path_to_target=target_path, substituent_list=substituent_list)


```
